---
# Production environment override
name:  fzcms_frankenphp_prod
services:
  php:
    build:
      context: .
      target: frankenphp_prod
    container_name: fzcms_frankenphp_prod
    image: fzcms_frankenphp_prod:7.4
    environment:
      APP_SECRET: ${APP_SECRET}
      # MERCURE_PUBLISHER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
      # MERCURE_SUBSCRIBER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
    ports:
      - "9090:80"
